pass: more portability patching

diff --git a/build/pass/patches/portability.patch b/build/pass/patches/portability.patch
--- a/build/pass/patches/portability.patch
+++ b/build/pass/patches/portability.patch
@@ -1,11 +1,15 @@
-$NetBSD: patch-src_password-store.sh,v 1.3 2018/06/14 16:08:39 leot Exp $
-
-Avoid non portable mkdir(1) `-v' parameter.
-
-diff -wpruN '--exclude=*.orig' a~/src/password-store.sh a/src/password-store.sh
+diff -wpruN --no-dereference '--exclude=*.orig' a~/src/password-store.sh a/src/password-store.sh
 --- a~/src/password-store.sh	1970-01-01 00:00:00
 +++ a/src/password-store.sh	1970-01-01 00:00:00
-@@ -344,7 +344,7 @@ cmd_init() {
+@@ -337,14 +337,14 @@ cmd_init() {
+ 
+ 	if [[ $# -eq 1 && -z $1 ]]; then
+ 		[[ ! -f "$gpg_id" ]] && die "Error: $gpg_id does not exist and so cannot be removed."
+-		rm -v -f "$gpg_id" || exit 1
++		rm -f "$gpg_id" || exit 1
+ 		if [[ -n $INNER_GIT_DIR ]]; then
+ 			git -C "$INNER_GIT_DIR" rm -qr "$gpg_id"
+ 			git_commit "Deinitialize ${gpg_id}${id_path:+ ($id_path)}."
  		fi
  		rmdir -p "${gpg_id%/*}" 2>/dev/null
  	else
@@ -41,6 +45,15 @@ diff -wpruN '--exclude=*.orig' a~/src/password-store.sh a/src/password-store.sh
  	set_gpg_recipients "$(dirname -- "$path")"
  	local passfile="$PREFIX/$path.gpg"
  	set_git "$passfile"
+@@ -584,7 +584,7 @@ cmd_delete() {
+ 
+ 	[[ $force -eq 1 ]] || yesno "Are you sure you would like to delete $path?"
+ 
+-	rm $recursive -f -v "$passfile"
++	rm $recursive -f "$passfile"
+ 	set_git "$passfile"
+ 	if [[ -n $INNER_GIT_DIR && ! -e $passfile ]]; then
+ 		git -C "$INNER_GIT_DIR" rm -qr "$passfile"
 @@ -618,7 +618,7 @@ cmd_copy_move() {
  	echo "$old_path"
  	[[ -e $old_path ]] || die "Error: $1 is not in the password store."
@@ -50,3 +63,21 @@ diff -wpruN '--exclude=*.orig' a~/src/password-store.sh a/src/password-store.sh
  	[[ -d $old_path || -d $new_path || $new_path == */ ]] || new_path="${new_path}.gpg"
  
  	local interactive="-i"
+@@ -626,7 +626,7 @@ cmd_copy_move() {
+ 
+ 	set_git "$new_path"
+ 	if [[ $move -eq 1 ]]; then
+-		mv $interactive -v "$old_path" "$new_path" || exit 1
++		mv $interactive "$old_path" "$new_path" || exit 1
+ 		[[ -e "$new_path" ]] && reencrypt_path "$new_path"
+ 
+ 		set_git "$new_path"
+@@ -643,7 +643,7 @@ cmd_copy_move() {
+ 		fi
+ 		rmdir -p "$old_dir" 2>/dev/null
+ 	else
+-		cp $interactive -r -v "$old_path" "$new_path" || exit 1
++		cp $interactive -r "$old_path" "$new_path" || exit 1
+ 		[[ -e "$new_path" ]] && reencrypt_path "$new_path"
+ 		git_add_file "$new_path" "Copy ${1} to ${2}."
+ 	fi
